export enum EEnvKey {
  NODE_ENV = 'NODE_ENV',
  TZ = 'TZ',
  LOG_LEVEL = 'LOG_LEVEL',
  IS_WRITE_LOG = 'IS_WRITE_LOG',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',
  SWAGGER_PATH = 'SWAGGER_PATH',
  PORT = 'PORT',
  BULL_MONITOR_PORT = 'BULL_MONITOR_PORT',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',
  BCRYPT_SALT_ROUND = 'BCRYPT_SALT_ROUND',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_REFRESH_SECRET_KEY = 'JWT_REFRESH_SECRET_KEY',
  JWT_ACCESS_TOKEN_EXPIRE = 'JWT_ACCESS_TOKEN_EXPIRE',
  JWT_REFRESH_TOKEN_EXPIRE = 'JWT_REFRESH_TOKEN_EXPIRE',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  // kafka
  KAFKA_BROKERS = 'KAFKA_BROKERS',
  KAFKA_CLIENT_ID = 'KAFKA_CLIENT_ID',
  KAFKA_GROUP_ID = 'KAFKA_GROUP_ID',
}

export enum EEnvironments {
  LOCAL = 'local',
  DEV = 'dev',
  TEST = 'test',
  UAT = 'uat',
  PRODUCTION = 'production',
}
